/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jethro James Aguilar
 */
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
import java.awt.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class signUP extends javax.swing.JFrame {
    /**
     * Creates new form signUP
     */
    public signUP() {
        initComponents();
        setResizable(false);
        
        jLabel9.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int response = JOptionPane.showConfirmDialog(null, 
                    "Are you sure you wish to go to the log-in page?", 
                    "Confirm", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE);
                    
                if (response == JOptionPane.YES_OPTION) {
                    logIN login = new logIN();
                    dispose();
                    login.setVisible(true);
                } else if (response == JOptionPane.NO_OPTION) {
                    // Do nothing, stay on the sign-up page
                }
            }
        });
        
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        // Thi code removes the maximize button
        setResizable(true); // Temporarily enable it to access the frame's peer
        setResizable(false); // Then disable it again
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl10 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JPasswordField();
        txt9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event Management System");
        setLocation(new java.awt.Point(280, 110));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(74, 31, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jetty\\Documents\\NetBeansProjects\\EventSystem\\logo.png")); // NOI18N
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 210, 140));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Plan your events with ease with");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Planorama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 480));

        jPanel2.setBackground(new java.awt.Color(186, 79, 84));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl2.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("SIGN-UP");
        jPanel2.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 62, -1, -1));

        lbl4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("First Name");
        jPanel2.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txt2.setBackground(new java.awt.Color(74, 31, 61));
        txt2.setFont(new java.awt.Font("Consolas", 1, 14));
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 234, 30));

        lbl5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("Last Name");
        jPanel2.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        lbl6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 255, 255));
        lbl6.setText("Age");
        jPanel2.add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lbl7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl7.setForeground(new java.awt.Color(255, 255, 255));
        lbl7.setText("Contact#");
        jPanel2.add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel8.setText("First Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 1115, -1, -1));

        lbl8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl8.setForeground(new java.awt.Color(255, 255, 255));
        lbl8.setText("Email");
        jPanel2.add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, 20));

        lbl9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl9.setForeground(new java.awt.Color(255, 255, 255));
        lbl9.setText("Username");
        jPanel2.add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jTextField11.setBackground(new java.awt.Color(74, 31, 61));
        jTextField11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 585, 180, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html>   <body style='font-family: Consolas; font-size: 11px; font-weight: bold; text-decoration: none;'>     <span style='color: white;'>Already have an account?</span>     <span style='color: rgb(74,31,61);'> Log-in</span>   </body> </html> ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 260, 40));

        jButton1.setBackground(new java.awt.Color(74, 31, 61));
        jButton1.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign-In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        lbl10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl10.setForeground(new java.awt.Color(255, 255, 255));
        lbl10.setText("Password");
        jPanel2.add(lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        lbl3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("Reference No.");
        jPanel2.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 145, -1, -1));

        txt1.setBackground(new java.awt.Color(74, 31, 61));
        txt1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt1MouseExited(evt);
            }
        });
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        jPanel2.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 440, 30));

        txt4.setBackground(new java.awt.Color(74, 31, 61));
        txt4.setFont(new java.awt.Font("Consolas", 1, 14));
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });
        jPanel2.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 41, 30));

        txt3.setBackground(new java.awt.Color(74, 31, 61));
        txt3.setFont(new java.awt.Font("Consolas", 1, 14));
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        jPanel2.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 200, 30));

        txt5.setBackground(new java.awt.Color(74, 31, 61));
        txt5.setFont(new java.awt.Font("Consolas", 1, 14));
        txt5.setForeground(new java.awt.Color(255, 255, 255));
        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });
        jPanel2.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 113, 30));

        txt6.setBackground(new java.awt.Color(74, 31, 61));
        txt6.setFont(new java.awt.Font("Consolas", 1, 14));
        txt6.setForeground(new java.awt.Color(255, 255, 255));
        txt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt6MouseExited(evt);
            }
        });
        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        jPanel2.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 270, 30));

        txt7.setBackground(new java.awt.Color(74, 31, 61));
        txt7.setFont(new java.awt.Font("Consolas", 1, 14));
        txt7.setForeground(new java.awt.Color(255, 255, 255));
        txt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt7MouseExited(evt);
            }
        });
        txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt7ActionPerformed(evt);
            }
        });
        jPanel2.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 173, 30));

        txt8.setBackground(new java.awt.Color(74, 31, 61));
        txt8.setFont(new java.awt.Font("Consolas", 1, 14));
        txt8.setForeground(new java.awt.Color(255, 255, 255));
        txt8.setEchoChar('\u25cf');
        txt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt8MouseExited(evt);
            }
        });
        txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8ActionPerformed(evt);
            }
        });
        jPanel2.add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 260, 30));

        txt9.setBackground(new java.awt.Color(74, 31, 61));
        txt9.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        txt9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 220, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 490, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int response = JOptionPane.showConfirmDialog(null, 
        "Do you wish to submit?", 
        "Confirm", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);
                    
    if (response == JOptionPane.YES_OPTION) {
        boolean a = false;
        logIN loginFrame = new logIN();
        if(txt2.getText().equals("")){ a = true; }
        if(txt2.getText().equals("")){ a = true; }
        if(txt4.getText().equals("")){ a = true; }
        if(txt3.getText().equals("")){ a = true; }
        if(txt5.getText().equals("")){ a = true; }
        if(txt6.getText().equals("")){ a = true; }
        if(txt7.getText().equals("")){ a = true; }
        if(txt8.getText().equals("")){ a = true; }
            
        if(a == true){
            JOptionPane.showMessageDialog(null, "Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
            
        if(a == false){
            String SUrl, SUser, SPass;
            SUrl = "jdbc:mysql://localhost:3306/planorama";
            SUser = "root";
            SPass = ""; 

            try (Connection con = DriverManager.getConnection(SUrl, SUser, SPass)) {
                String insertQuery = "INSERT INTO users(ref, fName, lName, age, contact, email, username, password) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

                // Validate age and contact are numeric
                int age;
                String ageText = txt4.getText().trim();    // Age is in txt4
                String contactText = txt5.getText().trim(); // Contact is in txt5

                // Debugging output to check values before parsing
                System.out.println("Age Text: " + ageText);
                System.out.println("Contact Text: " + contactText);

                // Regular expressions to check for numeric values
                if (!ageText.matches("\\d+")) {
                    JOptionPane.showMessageDialog(null, "Please enter valid numbers for Age and Contact fields.", "Error", JOptionPane.ERROR_MESSAGE);
                    return; // Exit method if validation fails
                }

                // Convert to integers after validation
                age = Integer.parseInt(ageText);

                try (PreparedStatement pstmt = con.prepareStatement(insertQuery)) {
                    pstmt.setString(1, txt1.getText().trim());   // ref
                    pstmt.setString(2, txt2.getText().trim());   // fName
                    pstmt.setString(3, txt3.getText().trim());   // lName
                    pstmt.setInt(4, age);                        // age
                    pstmt.setString(5, contactText);             // contact
                    pstmt.setString(6, txt6.getText().trim());   // email
                    pstmt.setString(7, txt7.getText().trim());   // username
                    pstmt.setString(8, txt8.getText().trim());   // password

                    int rowsAffected = pstmt.executeUpdate();

                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Account successfully signed up!");
                        // Redirect to login page
                        logIN login = new logIN();
                        dispose();
                        login.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to insert user.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // Print stack trace for detailed debugging
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // Print stack trace for detailed debugging
            }
        }
    } else if (response == JOptionPane.NO_OPTION) {
        // Do nothing, stay on the sign-up page
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5ActionPerformed

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6ActionPerformed

    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt7ActionPerformed

    private void txt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseExited
        String newRef = txt1.getText().trim();
        if (!newRef.isEmpty()) { // Only check if the ref is not empty
            String SUrl = "jdbc:mysql://localhost:3306/planorama";
            String SUser = "root";
            String SPass = "";

            String query = "SELECT COUNT(*) FROM users WHERE ref = ?";

            try (Connection conn = DriverManager.getConnection(SUrl, SUser, SPass);
                 PreparedStatement pstmt = conn.prepareStatement(query)) {

                pstmt.setString(1, newRef);
                ResultSet rs = pstmt.executeQuery();

                if (rs.next() && rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(null, "Reference number already exists, please use another one.", "Duplicate Reference", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Database connection error.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txt1MouseExited

    private void txt6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt6MouseExited
        
    }//GEN-LAST:event_txt6MouseExited

    private void txt7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt7MouseExited
        String newUsername = txt7.getText().trim();
        if (!newUsername.isEmpty()) { // Only check if the username is not empty
            String SUrl = "jdbc:mysql://localhost:3306/planorama";
            String SUser = "root";
            String SPass = "";

            String query = "SELECT COUNT(*) FROM users WHERE username = ?";

            try (Connection conn = DriverManager.getConnection(SUrl, SUser, SPass);
                 PreparedStatement pstmt = conn.prepareStatement(query)) {

                pstmt.setString(1, newUsername);
                ResultSet rs = pstmt.executeQuery();

                if (rs.next() && rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(null, "Username already exists, please use another one.", "Duplicate Username", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Database connection error.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txt7MouseExited
/*
    private boolean isPasswordFieldVisible = false;
    private String realPassword = "";
    
    private void toggleFieldVisibility() {
        if (isPasswordFieldVisible) {
            String password = String.valueOf(txt8.getPassword()); // Get password from txt8
            txt9.setText(password); // Set txt9 text to match txt8
            txt8.setVisible(false);
            txt9.setVisible(true);
        } else {
            String text = txt9.getText(); // Get text from txt9
            txt8.setText(text); // Set txt8 password to match txt9 text
            txt9.setVisible(false);
            txt8.setVisible(true);
        }
        isPasswordFieldVisible = !isPasswordFieldVisible; // Toggle visibility state
    } */

    private void txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8ActionPerformed

    private void txt8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JPasswordField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
